apiVersion: v1
kind: Service
metadata:
  name: {{ include "imio-plone.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "imio-plone.name" . }}-db
    helm.sh/chart: {{ include "imio-plone.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8100
      targetPort: 8100
      protocol: TCP
      name: db
  selector:
    app.kubernetes.io/name: {{ include "imio-plone.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
